# Generated by Django 4.1.3 on 2022-11-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='status',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('Fish', 'Fish'), ('Bug', 'Bug'), ('Sea Creature', 'Sea Creature')], default='Fish', max_length=12),
        ),
    ]
