# Generated by Django 4.1.3 on 2022-11-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_alter_achievement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='status',
            field=models.CharField(default='Not Caught', max_length=255),
            preserve_default=False,
        ),
    ]
