# Generated by Django 4.1.3 on 2022-11-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0005_achievement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('Fish', 'Fish'), ('Bug', 'Bug'), ('SeaCreature', 'Sea Creature')], default='Fish', max_length=12),
        ),
    ]
