# Generated by Django 4.1.3 on 2022-11-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0007_alter_achievement_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievement',
            new_name='Collection',
        ),
    ]
